from django.conf.urls import patterns, url
from competition import views

urlpatterns = patterns('',
  url(r'^category/$', views.category, name="category"),
  url(r'^$', views.competition_home, name="competition_home"),
  url(r'^info/$', views.competition_info, name="competition_info"),
  url(r'^sponsors/$', views.competition_sponsors, name="competition_sponsors"),
  url(r'^results/$', views.competition_results, name="competition_results"),
  url(r'^judge/register/$', views.judge_register, name="judge_register"),
  url(r'^judge/register/confirm/', views.judge_confirm, name="judge_confirm"),
  url(r'^register/$', views.register, name="register"),
  url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'competition_login.html'}, name="login"),
  url(r'^login/password/reset/$', 'django.contrib.auth.views.password_reset', {'post_reset_redirect' : '/competition/login/password/reset/done/'}, name="password_reset"),
  url(r'^login/password/reset/done/$', 'django.contrib.auth.views.password_reset_done'),
  url(r'^login/password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', {'post_reset_redirect' : '/competition/login/password/done/'}),
  url(r'^login/password/done/$', 'django.contrib.auth.views.password_reset_complete'), 
  url(r'^login/profile/$', views.login_result, name="brewer_profile"),
  url(r'^login/entry/$', views.add_entry, name="add_entry"),
  url(r'^login/address/$', views.address_change, name="address_change"),
  url(r'^login/entry/update/(?P<e_pk>\d+)', views.entry_update, name="entry_update"),
  url(r'^login/entry/remove/(?P<e_pk>\d+)', views.entry_remove, name="entry_remove"),
  url(r'^login/print/(?P<e_pk>\d+)', views.print_label, name="print_label"),
  url(r'^officertools/$', views.ot_home, name="ot_home"),
  url(r'^officertools/entries/$', views.ot_entries, name="ot_entries"),
  url(r'^officertools/brewers/$', views.ot_brewers, name="ot_brewers"),
  url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '../login/'}, name="logout"),
  url(r'^locations/$', views.competition_locations, name="competition_locations"),
)
